### ISSUE TITLE
Probleme de recherche

### ISSUE THREAD

**Issue by blablanumerodeux** [cocazoulou/couchpotato.provider.t411#11]
Hello, 
Lorsque je recherche "fou d'irene" sur T411 je trouve 4 resultats, mais avec CP je ne trouve rien, voila un bout de log : 

```
05-17 16:39:16 INFO [hpotato.core.plugins.base] Opening url: get https://api.t411.ch/torrents/search/fou%20direne?limit=200&cat=631, data: [] 
```

Je pense que c'est a cause de l'apostrophe car quand je recherche "fou direne" (sans l'apostrophe) dans T411 alors je ne trouve aucuns resultats.

**Comment by cocazoulou** [comment]
@blablanumerodeux Utilise tu un autre plugin qui changerais la langue retourné par themoviedb? Car la recherche renome fou d'irene par Me, Myself & Irene.

05-18 00:16:26 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/fou+d%27irene/?limit=5, data: []
05-18 00:16:26 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=ngram&query=fou+d%27irene, data: []
05-18 00:16:26 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=&t=fou+d%27irene, data: []
05-18 00:16:26 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/2123?api_key=xxx&append_to_response=alternative_titles, data: []
05-18 00:16:26 INFO [providers.info.themoviedb] Found: [u'Me, Myself & Irene (2000)']
05-18 00:16:59 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt0183505/, data: []
05-18 00:17:00 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt0183505?api_key=xxx&append_to_response=alternative_titles, data: []
05-18 00:17:00 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt0183505/?ignore=1, data: []
05-18 00:17:00 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt0183505, data: []
05-18 00:17:00 INFO [ie.providers.info.omdbapi] Found: Me, Myself & Irene (2000)
05-18 00:17:00 INFO [ie.providers.info.omdbapi] Found: Me, Myself & Irene (2000)
05-18 00:17:00 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt0183505?api_key=xxx&append_to_response=alternative_titles, data: []
05-18 00:17:00 INFO [hpotato.core.plugins.base] Opening url: get http://ia.media-imdb.com/images/M/MV5BMTg5NzIzMzM3M15BMl5BanBnXkFtZTYwMjAwMzg5._V1_SX300.jpg, data: []
05-18 00:17:00 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt0183505/, data: []
05-18 00:17:00 INFO [core.media.movie.searcher] Search for Me, Myself & Irene in 720p ignoring ETA
05-18 00:17:00 INFO [hpotato.core.plugins.base] Opening url: post https://api.t411.ch/auth, data: ['username', 'password']
05-18 00:17:02 INFO [hpotato.core.plugins.base] Opening url: get https://api.t411.ch/torrents/search/me%20myself%20irene?limit=200&cat=631, data: []

**Comment by blablanumerodeux** [comment]
J'ai activé l'option debug et j'ai compris pourquoi il ne trouvait rien. Les fichiers étaient exclus à cause de leurs taille ou de la qualité.
Merci pour le coup de main.
