### ISSUE TITLE
age of release not picked one T411 and some BR-releases not found

### ISSUE THREAD

**Issue by turbalf** [cocazoulou/couchpotato.provider.t411#3]
Hello,
j'ai tenté la manip sur plusieurs films, pas d'âge affiché dans les recherches.
de plus (mais c'est pareil sur tous les plugins), les releases BR ne sont trouvées que pour certains films alors qu'elles existent bel et bien sur le site (malgré tous les filtres désactivés).
Merci pour le boulot effectué, c'est 
![nouvelle image bitmap](https://cloud.githubusercontent.com/assets/12201422/10896441/60247092-81ba-11e5-91e3-d6255a92c4c6.jpg)
quand même le plugin qui marche le mieux chez moi !

**Comment by cocazoulou** [comment]
@turbalf 
Pour l'age des releases c'est ajouté, tu as seulement a updater le plugin.
Pour les releases BR qui ne sont pas trouvé, pourrais-tu activé le debuging, effectuez une recherche avec un film ou tu sais qu'il manque des releases.
Puis uploader le fichier de log et le lien vers une des releases manquant SVP.

Merci

**Comment by turbalf** [comment]
Super ça marche pour les dates !
Et ça m'a trouvé les releases BR, j'ai dû confondre avec un des autres plugins que j'ai testé !
Merci beaucoup pour ton taf en tous cas !
Petite question vu que t'as l'air de maîtriser, tu saurais comment bidouiller le calcul du score pour qu'une release 2D ne puisse pas passer devant une release 3D (genre booster le score des 3D), idem pour qu'un 1080p ne passe pas devant un BR, parce que c'est obscur ce calcul et du coup ça ne fait pas tjrs ce qu'on veut (perso m'en fous des points, si y a un iso BR, je ne veux pas savoir le score des releases 1080p, pareil pour 3D/2D).
Merci encore @++

**Comment by cocazoulou** [comment]
@turbalf 
Tu as juste a aller dans Settings puis Qualities. Tu peux créer tes profiles de qualité a cette endroit. C'est pas mal le mieux qui pourrais te convenir.

Merci

**Comment by turbalf** [comment]
Hello,
c'est déjà ce que j'ai fait, un profil HD avec dans l'ordre BR-3D, 1080-3D, BR et 1080, et pour des raisons de calcul de score obscures, la plupart du temps les releases 1080 tout court font un meilleur score que le reste donc c'est ce que CP snatche alors que des BR et/ou des 3D sont disponibles.
Pour 3D j'ai changé le bonus pour les mots mais du coup ça vaut aussi pour les autres mots préférés et ça peut déséquilibrer le calcul global, et pour les BR y pas ou peu de différences au niveau du nom donc je ne peux pas jouer là-dessus et je ne sais pas où rendre les BR prioritaires indépendamment du score.
En fait ce qui serait top c'est que le score ne joue qu'au sein d'une même qualité pour départager plusieurs releases, mais que si dispo, le top de la liste des qualités soit toujours devant !

**Comment by cocazoulou** [comment]
@turbalf 
J'ai regarder plus en détail le calcul du score pour les releases et probablement ce qui te cause du trouble c'est que 30% des seeders et 15% des leechers sont rajouté dans le score et que les releases BD disk n'ont jamais beaucoup de Seeders et Leechers. Cependant j'ai veux que tu avais fais une  feature request pour CouchPotato, c'est la meilleur chose a faire.
Merci
