### ISSUE TITLE
Did a test, got this error.  Is this a "normal" error I can ignore ?

### ISSUE THREAD

**Issue by pducharme** [cocazoulou/couchpotato.provider.t411#6]
Hi, I got this error when I did a 1st test after installing this t411 plugin... 

From the Couchpotato LOG :

[hpotato.core.plugins.base] Opening url: post https://api.t411.in/auth, data: ['username', 'password']
[hpotato.core.plugins.base] Opening url: get https://api.t411.in/torrents/search/bridge%20of%20spies?limit=200&cat=631, data: []

**11-19 10:15:31 ERROR
[ couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/event.py", line 15, in runHandler return handler(_args, *_kwargs) File "/opt/couchpotato/couchpotato/core/media/_base/providers/base.py", line 233, in search self._searchOnTitle(title, media, quality, results) File "/config/data/custom_plugins/t411/main.py", line 45, in _searchOnTitle for entry in output['torrents']: KeyError: 'torrents' encoding=UTF-8 debug=False args=['--config_file=/config/config.ini', '--data_dir=/config/data'] app_dir=/opt/couchpotato data_dir=/config/data desktop=None options=Namespace(config_file='/config/config.ini', console_log=False, daemon=False, data_dir='/config/data', debug=False, pid_file='/config/data/couchpotato.pid', quiet=False)**

**Comment by cocazoulou** [comment]
Hello @pducharme 

Yes it's an error you can ignore. I have an updated version that I will upload tonight that will resolve that error.

Thanks
