### ISSUE TITLE
small issue but big impact : torrents never found

### ISSUE THREAD

**Issue by leelouch** [cocazoulou/couchpotato.provider.t411#7]
line 45:        if 'torrent' in output: 
must be replaced by : 
line 45:       if 'torrents' in output:

correct ? 
otherwise torrents are never found !

**Comment by niemes** [comment]
Thank you very MUCH xD...

**Comment by cocazoulou** [comment]
Hello @leelouch Could you test with the branch Patch-Issue7. I didn't have access to my dev environemebt to test it.

Thanks

**Comment by leelouch** [comment]
hello @cocazoulou,
just took a look to your patch, I am already running with a similar one, (only one lettre change ;) ).
it is working, no problem.
