### ISSUE TITLE
Fichiers installés mais T411 n'apparait pas

### ISSUE THREAD

**Issue by gogui51** [cocazoulou/couchpotato.provider.t411#8]
Bonjour,

j'ai déplacé les fichiers dans le bon répertoire (je pense !) mais même après un "restart" le provider n'apparait pas.

Voici où sont copier les fichiers :
osmc@osmc:/home/couchpotato/.couchpotato/customs_plugin/t411$ ls
init.py main.py

Je ne comprends pas où j'ai merdé !

Merci pour votre aide !
Greg

**Comment by leelouch** [comment]
regarde tu n'aurais pas un probleme de droits
fait ls -la sur le répertoire /home/couchpotato/.couchpotato/customs_plugin
et donne les meme droits au répertoire t411 , le mieux c'est de changer l'owner et group du repertoir

**Comment by gogui51** [comment]
Bonsoir,
je viens de changer tous les chmod comme ceci, rien n'y fait...
'''
drwxr-xr-x 2 couchpotato couchpotato 4096 déc.  22 00:39 .
drwxr-xr-x 3 root        root        4096 déc.  22 00:26 ..
-rwxr-xr-x 1 couchpotato couchpotato 2061 déc.  22 00:39 **init**.py
-rwxr-xr-x 1 couchpotato couchpotato 4980 déc.  22 00:39 main.py
'''
Une autre idée ?
Merci beaucoup !

**Comment by Serane** [comment]
Bonjour, 
Je rencontre la même situation sur un poste Windows. 

Ayant déjà installé ce plugin sur d'autres machines par le passé, je suis surpris de ce comportement.

**Comment by leelouch** [comment]
@gogui51 ton directory ".." est root root , c'est bizarre, est ce que tout ton répertoire couchpotato est root ? 
ca devrai être au moins couchpotato, root

**Comment by cocazoulou** [comment]
@gogui51 
Je ne sais pas si c'est en copiant le texte mais le fichier init.py doit être `__init__.py`
Ensuite dans le repertoire custom_plugins tu doit avoir un fichier `__init__.py` aussi.
Pourrais-tu me fournir les startup Args pour couchpotato? Tu va les trouvé dans les settings dans la section About.
Merci

**Comment by gogui51** [comment]
Salut, je rentre de congés, je vais me repencher sur couch et sur T411 cette semaine.
Merci de ta réponse, je regarde ça.

Et bien sur bonne année pleine de movies :)

**Comment by gogui51** [comment]
Bonsoir,

bon j'ai tout supprimé et réinstallé, je ne sais pas pourquoi mais maintenant ça fonctionne...

Voici mon chmod pour les prochains : 
osmc@osmc:/home/couchpotato/.couchpotato/custom_plugins/t411$ ls -l
total 24
-rwxrwxrwx 1 root        root        2061 janv.  7 19:35 **init**.py
-rw-rw-rw- 1 couchpotato couchpotato 1589 janv.  7 19:45 **init**.pyc
-rwxrwxrwx 1 root        root        4980 janv.  7 19:35 main.py
-rw-rw-rw- 1 couchpotato couchpotato 5013 janv.  7 19:45 main.pyc

Merci beaucoup, je vais maintenant tester le plugin.

:+1:
